development:
  cloud_name: tatangtech
  api_key: '388455595119354'
  api_secret: usWHzmRlRpnLDg4wr9MRfMFclAA
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: tatangtech
  api_key: '388455595119354'
  api_secret: usWHzmRlRpnLDg4wr9MRfMFclAA
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: tatangtech
  api_key: '388455595119354'
  api_secret: usWHzmRlRpnLDg4wr9MRfMFclAA
  enhance_image_tag: true
  static_file_support: false